# Generated by Django 5.1.15 on 2026-08-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "raw_event",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("webhook_event_id", models.CharField(max_length=128, unique=True)),
                (
                    "line_message_id",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("user", "1 對 1"), ("group", "群組"), ("room", "多人聊天室")],
                        max_length=16,
                    ),
                ),
                ("source_id", models.CharField(max_length=128)),
                ("sender_id", models.CharField(blank=True, max_length=128, null=True)),
                ("message_type", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待處理"),
                            ("SUCCESS", "已成功備份"),
                            ("FAILED", "重試多次後仍失敗"),
                            ("SKIPPED", "不符合備份條件"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("target_ref", models.CharField(blank=True, max_length=256, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("line_timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_records",
                        to="backup.rawevent",
                    ),
                ),
            ],
            options={
                "db_table": "backup_record",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["status"], name="backup_record_status_idx")],
            },
        ),
    ]
